# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f8c04a84aad57e6932b7c28f795eca6f3401287ef5564cdf0aae49bb626452c8a1937c445041206c31c4ca091e54a48854d0bc991436789daa01980743de3bf

test:
  secret_key_base: c66f93a71b754b5d02a00f42ee7601d385629d17f55b6be645e6da2ee0c2d4645fd191b8c7d2f79e4fc35b04c14d4830076ef73a1594a2adcc8f6439486dec74

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
